### PR TITLE
INTLY-1201 use master image tag in master branch

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by tremes** [comment]
@maleck13  Please check (and the corresponding issue). I would like to do this for all our operators (so that we test the latest&greatest stuff)

**Comment by maleck13** [comment]
ping @mikenairn. @tremes I think this is fine as long as we cut a release of the operator with a proper tag that changes this and is used from the installer

**Comment by mikenairn** [comment]
Ideally we would have these set to master, but if we do, we have to make sure that we have these set to an explicit tag prior to creating a release as @maleck13 has said. I can see this not happening if we rely on people doing this manually.

**Comment by mikenairn** [comment]
This comes back to what was discussed previously about our own components not being treated any differently from external middleware products. If we are including un-released versions of this, why not 3scale, rhsso etc...

**Comment by maleck13** [comment]
So I think lets go ahead with this change. I will add something to the release doc in the installer to say (these components we control, may also need a release creating)

**Comment by maleck13** [comment]
needs a rebase but then good to merge

**Comment by maleck13** [comment]
https://github.com/integr8ly/installation/pull/524

**Comment by maleck13** [comment]
@tremes We need to update the release process for the operator. It should match the way we do it for the installer. IE create a branch update the image to the release version commit and push then create a tag

**Comment by trepel** [comment]
I asked @mikenairn and he is aware of this (the need for the change of release process). Merging this one.

**Comment by mikenairn** [comment]
@trepel @tremes Can you update the release steps here to reflect what will now need to be done https://github.com/integr8ly/tutorial-web-app-operator#release. This will be up to the people in charge of the operator to make sure these releases are created properly and things get updated as expected.

**Pull request merged**
